// This file is generated by forge doc. Do not edit manually.
// Re-run `forge doc` to update.

export const sidebar = [
    {
      text: "src",
      items: [
        { text: "ERC20Mock", link: "/src/contract.ERC20Mock" },
      ],
    },
    {
      text: "src/DeployManager",
      items: [
        {
          text: "Contracts",
          collapsed: true,
          items: [
            { text: "DeployManager", link: "/src/DeployManager/contract.DeployManager" },
          ],
        },
        {
          text: "Interfaces",
          collapsed: true,
          items: [
            { text: "IDeployManager", link: "/src/DeployManager/interface.IDeployManager" },
          ],
        },
      ],
    },
    {
      text: "src/ERC1155Airdroper",
      items: [
        { text: "ERC1155Airdroper", link: "/src/ERC1155Airdroper/contract.ERC1155Airdroper" },
      ],
    },
    {
      text: "src/ERC20Airdroper",
      items: [
        { text: "ERC20Airdroper", link: "/src/ERC20Airdroper/contract.ERC20Airdroper" },
      ],
    },
    {
      text: "src/ERC721Airdroper",
      items: [
        { text: "ERC721Airdroper", link: "/src/ERC721Airdroper/contract.ERC721Airdroper" },
      ],
    },
    {
      text: "src/LiniarVesting",
      items: [
        {
          text: "Contracts",
          collapsed: true,
          items: [
            { text: "Vesting", link: "/src/LiniarVesting/contract.Vesting" },
          ],
        },
        {
          text: "Interfaces",
          collapsed: true,
          items: [
            { text: "IVesting", link: "/src/LiniarVesting/interface.IVesting" },
          ],
        },
        {
          text: "Libraries",
          collapsed: true,
          items: [
            { text: "VestingLib", link: "/src/LiniarVesting/library.VestingLib" },
          ],
        },
      ],
    },
    {
      text: "src/UtilityContract",
      items: [
        {
          text: "Abstract Contracts",
          collapsed: true,
          items: [
            { text: "AbstractUtilityContract", link: "/src/UtilityContract/abstract.AbstractUtilityContract" },
          ],
        },
        {
          text: "Interfaces",
          collapsed: true,
          items: [
            { text: "IUtilityContract", link: "/src/UtilityContract/interface.IUtilityContract" },
          ],
        },
      ],
    },
]
